POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Enzo",
  "email": "enzo@gmail.com",
  "password": "123456"
}
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"email": "enzo@gmail.com",
"password": "123456"
}
### - Users
GET http://localhost:8080/api/users?page=0&size=10
Authorization: Bearer {{TOKEN}}
###
GET http://localhost:8080/api/users/2
Authorization: Bearer {{TOKEN}}
### - Courses
GET http://localhost:8080/api/courses?page=0&size=10
Authorization: Bearer {{TOKEN}}
###
GET http://localhost:8080/api/courses/1
Authorization: Bearer {{TOKEN}}
###
POST http://localhost:8080/api/courses
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "title": "Matemática Avançada 1",
  "description": "Cálculo, derivadas e integrais",
  "workloadHours": 60
}
###
PUT http://localhost:8080/api/courses/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "title": "Matemática Avançada 1",
  "description": "Cálculo, derivadas e integrais",
  "workloadHours": 60,
  "active": false
}
###
DELETE http://localhost:8080/api/courses/1
Authorization: Bearer {{TOKEN}}
###
POST http://localhost:8080/api/enrollments
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "courseId": 1
}
###
GET http://localhost:8080/api/me/courses
Authorization: Bearer {{TOKEN}}
###
GET http://localhost:8080/api/enrollments/users/2
Authorization: Bearer {{TOKEN}}
###
GET http://localhost:8080/api/enrollments/courses/1
Authorization: Bearer {{TOKEN}}
