### GET request to example server
GET http://localhost:8080
###
GET http://localhost:8080/api/users
###
GET http://localhost:8080/api/users/9999
###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Enzo",
  "email": "enzo@gmail.com"
}
###
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "name": "Carlos",
  "email": "carlos@gmail.com"
}
###
DELETE http://localhost:8080/api/users/1

###
GET http://localhost:8080/api/courses
###
GET http://localhost:8080/api/courses/1
###
POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "title": "Matemática Avançada 1",
  "description": "Calculo, derivadas e integrais",
  "workloadHours": 60
}
###
PUT http://localhost:8080/api/courses/1
Content-Type: application/json

{
  "title": "Matemática Avançada 1",
  "description": "Calculo, derivadas e integrais",
  "workloadHours": 60,
  "active": false
}
###
DELETE http://localhost:8080/api/courses/1
###
POST http://localhost:8080/api/enrollments
Content-Type: application/json

{
  "userId": 1,
  "courseId": 1
}
###
GET http://localhost:8080/api/enrollments/users/1
###
GET http://localhost:8080/api/enrollments/courses/1